spring.application.name=digitalqueue

# Puerto del backend
server.port=8080

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/digital_queue_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evita consultas abiertas fuera del service
spring.jpa.open-in-view=false