spring.application.name=digitalqueue
server.port=8080

# PostgreSQL dentro de Docker Compose
spring.datasource.url=jdbc:postgresql://postgres:5432/digital_queue_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Cassandra dentro de Docker Compose
spring.cassandra.contact-points=cassandra:9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=digital_queue_metrics
spring.cassandra.schema-action=none
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
